# Python File Objects

### Instructions

* Complete the programming exercises below.
* Delete or comment out the line of code in each cell which says `raise NotImplementedError()` and replace it with your own.

### Exercises

## Path to file or directory

Sometimes you want to work with files in a particular directory. In order to do that you need to get the path. There are a couple different ways you can do that.

In Windows you can open a command prompt (in Mac a terminal window) and drag the file or folder to the command prompt and the path will display in the window. You can then copy the path and paste it into your code. It will probably look something like this.

`C:\Users\UserName\Documents`

To use the path in your code, you will want to assign it to a variable.

`file_path = 'C:\Users\UserName\Documents'`

Windows users will quickly realize that their path as Windows formats it causes error when used without some modification. (Mac users won't have this problem because Macs format the path in a way that Python can use it without modification.) This is a problem for Windows users because Windows uses backslash (\) characters in the file path. In Python, the backslash character is a special character. To use special characters in strings in Python, they need to have an escape character added before the special character. In Python, the escape character is the backslash (\). One option Windows users have is to add an extra backslash in front of every backslash in the path. It will look like this.

`file_path = 'C:\\Users\\UserName\\Documents'`

Another option is to change each backslash (\) to a forward slash (/).

`file_path = 'C:/Users/UserName/Documents'`

Another option is to format the string as a raw string. This option saves a lot of typing. This is done in Python by adding a lowercase `r` in front of the quotation marks for the string. This is a signal to Python to treat the string exactly as it is formatted and consider any special characters included in the string as literal characters.

`file_path = r'C:\Users\UserName\Documents'`

Another option is to use a graphical user interface included in Python (called tkinter) to open a dialog window and allow the user to select the file or directory of interest. Run the code block below to use the file dialog to select the files directory included in the repository for this assignment. (Be sure to select the inner files directory which actually contains the files needed for the assignment.)

In [9]:
# Have user select the folder with the needed files.
import tkinter as tk
from tkinter import filedialog

root = tk.Tk()
root.lift()
root.withdraw()

# This code block will open a specific file. (Uncomment the lines after this comment to use them.)
#print('Opening dialogue box for file selection. Please choose a file.')
#file_path = filedialog.askopenfilename()
#print('File selected:')

# This code block will get a directory path. (Uncomment the lines after this comment to use them.)
print('Opening dialogue box for folder selection. Please choose a folder.')
file_path = filedialog.askdirectory()
print('Folder selected:')

print(file_path)

Opening dialogue box for folder selection. Please choose a folder.
Folder selected:
/Users/vartika/Desktop/01 Vartika/01_software_coding/python combine files /exerPythCombineFiles-1/FileTypes

## Working with different file types in Python

The purpose of this assignment is to see how to work with different file types in Python. Run the code block below to see the different types of files included in the folder.

In [10]:
# Make sure correct files are recognized.

import os
import pandas as pd

# List the files in the directory.
files = os.listdir(file_path)
print('All files in folder: ', files, '\n')

# List of file types we want to add
file_types = ['xlsx','csv','json','xml']

# create a list of files for each file type
files_csv = [f for f in files if f[-3:] == 'csv']
files_xlsx = [f for f in files if f[-4:] == 'xlsx']
files_json = [f for f in files if f[-4:] == 'json']
files_xml = [f for f in files if f[-3:] == 'xml']

print('CSV files: ', files_csv, '\nExcel files: ', files_xlsx, '\nJSON files: ',files_json, '\nXML files: ', files_xml)

All files in folder:  ['EXCELtest2.xlsx', 'CSVtest3.csv', 'CSVtest2.csv', 'XMLtest4.xml', 'JSONtest4.json', 'EXCELtest.xlsx', 'XMLtest2.xml', 'EXCELtest3.xlsx', 'XMLtest3.xml', 'JSONtest.json', 'JSONtest2.json', 'CSVtest.csv', 'JSONtest3.json', 'Combine multiple file types with same columns into dataframe.py', 'Combine multiple file types with same columns into dataframe.ipynb', 'XMLtest.xml']

CSV files:  ['CSVtest3.csv', 'CSVtest2.csv', 'CSVtest.csv']
Excel files:  ['EXCELtest2.xlsx', 'EXCELtest.xlsx', 'EXCELtest3.xlsx']
JSON files:  ['JSONtest4.json', 'JSONtest.json', 'JSONtest2.json', 'JSONtest3.json']
XML files:  ['XMLtest4.xml', 'XMLtest2.xml', 'XMLtest3.xml', 'XMLtest.xml']

Write you answers as comments in the cell below.

* What types of files are included in the folder? List the file extensions and how many of each type you see.

In [ ]:

# YOUR CODE HERE
# 3 CSV files with .csv as file extension
# 3 excel files with .xlsx as file extension
# 4 JSON files with .json as file extension
# 4 XML files with .xml sa file extension

## Creating a Pandas dataframe

Run the code block below to read each data file and combine them into a Pandas dataframe.

In [11]:
import json
import requests 
import xml.etree.ElementTree as ET

# Iterate through the files in the directory and append each one into the dataframe.
# This will only work correctly if the files have the exact same column names.
df_list = []
for f in files_csv:
    data = pd.read_csv(str(file_path) + '/' + str(f), index_col=None, header=0)
    data['Source'] = f
    df_list.append(data)
    
for f in files_xlsx:
    data = pd.read_excel(str(file_path) + '/' + str(f))
    data['Source'] = f
    df_list.append(data)
    
# Iterate through the json files and add data from each to a list.
json_list = []
for f in files_json:
    with open(str(file_path) + '/' + str(f)) as json_file:
        json_obj = json.load(json_file)
        json_obj['Source'] = f
        json_list.append(json_obj.copy())
# Turn the combined list into a dataframe.
data = pd.DataFrame(json_list)
# Add the data frame to the list of dataframes.
df_list.append(data)
    
# Iterate through the xml files and add data from each to a list.
xml_list = []
for f in files_xml:
    # create element tree object 
    tree = ET.parse(str(file_path) + '/' + str(f))
    # get root element 
    root = tree.getroot()
    # create dictionary from XML tags and values
    itemdict = {}
    for item in root:
        itemdict[item.tag] = item.text
    itemdict['Source'] = f
    xml_list.append(itemdict.copy())
# Turn the combined list into a dataframe.
data = pd.DataFrame(xml_list)
# Add the data frame to the list of dataframes.
df_list.append(data)

# Combine all the data frames in the list into a single data frame.    
df =  pd.concat(df_list, axis=0, ignore_index=True, sort=False)

# See how many rows the data frame has.
print(len(df.index))

# Show the data in the data frame.
df

20

              name                 date height weight           Source
0    Vartika Test1              4/10/20    185     95     CSVtest3.csv
1   Vartika Test 2               6/7/21    172     91     CSVtest3.csv
2     Brock Bricks            4/10/2019    185     95     CSVtest2.csv
3       Jack Brack             6/7/2019    172     91     CSVtest2.csv
4       Jack Smith             4/1/2019    185     91      CSVtest.csv
5       Jack Black             4/2/2019    183     91      CSVtest.csv
6      Rock Royden  2019-05-02 00:00:00    160     52  EXCELtest2.xlsx
7    Brandon Snads  2019-10-02 00:00:00    175     80  EXCELtest2.xlsx
8        Jen Smith  2019-05-02 00:00:00    153     50   EXCELtest.xlsx
9        Sam Smith  2019-01-02 00:00:00    160     55   EXCELtest.xlsx
10   Vartika Test3  2020-05-02 00:00:00    153     50  EXCELtest3.xlsx
11   Vartika Test4  2021-01-02 00:00:00    160     55  EXCELtest3.xlsx
12   Vartika Test5           09/02/2020    170     75   JSONtest4.json
13      Jane Smith           09/02/2019    170     75    JSONtest.json
14    Jane Jackson           09/03/2019    172     74   JSONtest2.json
15   Becky Jackson           04/03/2019    165     70   JSONtest3.json
16   Vartika Test6           02/08/2020    180    100     XMLtest4.xml
17     John Smithe           03/08/2019    185    101     XMLtest2.xml
18    Brett Smithe           05/08/2019    179     99     XMLtest3.xml
19      John Smith           02/08/2019    180    100      XMLtest.xml

## Saving a dataframe to csv

Run the code block below to save your new dataframe as a csv file.

In [12]:
# Save the dataframe to a new combined csv file.

# Add today's date to the name of the new file.
from datetime import date
today = date.today()
print(today)

filename = str(file_path) + '/' + 'NewCombinedFile_' + str(today) + '.csv'
print(filename)

df.to_csv(filename, index=False)
print('File saved.')

2022-11-26
/Users/vartika/Desktop/01 Vartika/01_software_coding/python combine files /exerPythCombineFiles-1/FileTypes/NewCombinedFile_2022-11-26.csv
File saved.

## Create additional data files

Create a new data file for each type included in the folder. (You can use Excel to modify the content in the .xlsx and .csv files and save them under a new name in the same folder. You can use VSCode or Notepad++ to modify the content of an .xml and .json file and save those under a new name in the same folder.) Make sure you create at least one additional file for each type of data file in the folder.

Enter code in the cell below.

* Create a variable called `file_path` which contains the path to the folder where all the data files are included. You can use any of the methods described at the beginning of the notebook (Manually copy the path or copy the code to create a file dialog to choose the correct folder.)

In [15]:

# YOUR CODE HERE
print('Opening dialogue box for folder selection. Please choose a folder.')
file_path = filedialog.askdirectory()
print('Folder selected:')

print(file_path)

Opening dialogue box for folder selection. Please choose a folder.
Folder selected:
/Users/vartika/Desktop/01 Vartika/01_software_coding/python combine files /exerPythCombineFiles-1/FileTypes

Enter code in the cell below.

* Add code in the cell below to list the files in the folder and create lists for each data file type. (Hint - It's OK to reuse code from earlier in the assignment.)

In [16]:

# YOUR CODE HERE
import os
import pandas as pd

# List the files in the directory.
files = os.listdir(file_path)
print('All files in folder: ', files, '\n')

# List of file types we want to add
file_types = ['xlsx','csv','json','xml']

# create a list of files for each file type
files_csv = [f for f in files if f[-3:] == 'csv']
files_xlsx = [f for f in files if f[-4:] == 'xlsx']
files_json = [f for f in files if f[-4:] == 'json']
files_xml = [f for f in files if f[-3:] == 'xml']

print('CSV files: ', files_csv, '\nExcel files: ', files_xlsx, '\nJSON files: ',files_json, '\nXML files: ', files_xml)

All files in folder:  ['EXCELtest2.xlsx', 'CSVtest3.csv', 'CSVtest2.csv', 'XMLtest4.xml', 'JSONtest4.json', 'XMLtest5.xml', 'EXCELtest.xlsx', 'CSVtest4.csv', 'JSONtest5.json', 'XMLtest2.xml', 'EXCELtest3.xlsx', 'XMLtest3.xml', 'JSONtest.json', 'JSONtest2.json', 'EXCELtest4.xlsx', 'CSVtest.csv', 'JSONtest3.json', 'NewCombinedFile_2022-11-26.csv', 'Combine multiple file types with same columns into dataframe.py', 'Combine multiple file types with same columns into dataframe.ipynb', 'XMLtest.xml']

CSV files:  ['CSVtest3.csv', 'CSVtest2.csv', 'CSVtest4.csv', 'CSVtest.csv', 'NewCombinedFile_2022-11-26.csv']
Excel files:  ['EXCELtest2.xlsx', 'EXCELtest.xlsx', 'EXCELtest3.xlsx', 'EXCELtest4.xlsx']
JSON files:  ['JSONtest4.json', 'JSONtest5.json', 'JSONtest.json', 'JSONtest2.json', 'JSONtest3.json']
XML files:  ['XMLtest4.xml', 'XMLtest5.xml', 'XMLtest2.xml', 'XMLtest3.xml', 'XMLtest.xml']

Write you answers as comments in the cell below.

* What types of files are included in the folder? List the file extensions and how many of each type you see.

In [ ]:

# YOUR CODE HERE
# 4 CSV files with .csv as file extension
# 4 excel files with .xlsx as file extension
# 5 JSON files with .json as file extension
# 5 XML files with .xml sa file extension

Enter code in the cell below.

* Add code in the cell below to read each data file and combine them into a Pandas dataframe and display the dataframe. (Hint - It's OK to reuse code from earlier in the assignment.)

In [17]:

# YOUR CODE HERE
import json
import requests 
import xml.etree.ElementTree as ET

# Iterate through the files in the directory and append each one into the dataframe.
# This will only work correctly if the files have the exact same column names.
df_list = []
for f in files_csv:
    data = pd.read_csv(str(file_path) + '/' + str(f), index_col=None, header=0)
    data['Source'] = f
    df_list.append(data)
    
for f in files_xlsx:
    data = pd.read_excel(str(file_path) + '/' + str(f))
    data['Source'] = f
    df_list.append(data)
    
# Iterate through the json files and add data from each to a list.
json_list = []
for f in files_json:
    with open(str(file_path) + '/' + str(f)) as json_file:
        json_obj = json.load(json_file)
        json_obj['Source'] = f
        json_list.append(json_obj.copy())
# Turn the combined list into a dataframe.
data = pd.DataFrame(json_list)
# Add the data frame to the list of dataframes.
df_list.append(data)
    
# Iterate through the xml files and add data from each to a list.
xml_list = []
for f in files_xml:
    # create element tree object 
    tree = ET.parse(str(file_path) + '/' + str(f))
    # get root element 
    root = tree.getroot()
    # create dictionary from XML tags and values
    itemdict = {}
    for item in root:
        itemdict[item.tag] = item.text
    itemdict['Source'] = f
    xml_list.append(itemdict.copy())
# Turn the combined list into a dataframe.
data = pd.DataFrame(xml_list)
# Add the data frame to the list of dataframes.
df_list.append(data)

# Combine all the data frames in the list into a single data frame.    
df =  pd.concat(df_list, axis=0, ignore_index=True, sort=False)

# See how many rows the data frame has.
print(len(df.index))

# Show the data in the data frame.
df

48

,name,date,height,weight,Source
0,Vartika Test1,4/10/20,185,95,CSVtest3.csv
1,Vartika Test 2,6/7/21,172,91,CSVtest3.csv
2,Brock Bricks,4/10/2019,185,95,CSVtest2.csv
3,Jack Brack,6/7/2019,172,91,CSVtest2.csv
4,Vartika Test1,4/10/20,185,95,CSVtest4.csv
5,Vartika Test 2,6/7/21,172,91,CSVtest4.csv
6,Vartika Test7,6/7/22,172,91,CSVtest4.csv
7,Jack Smith,4/1/2019,185,91,CSVtest.csv
8,Jack Black,4/2/2019,183,91,CSVtest.csv
9,Vartika Test1,4/10/20,185,95,NewCombinedFile_2022-11-26.csv
10,Vartika Test 2,6/7/21,172,91,NewCombinedFile_2022-11-26.csv
11,Brock Bricks,4/10/19,185,95,NewCombinedFile_2022-11-26.csv
12,Jack Brack,6/7/19,172,91,NewCombinedFile_2022-11-26.csv
13,Jack Smith,4/1/19,185,91,NewCombinedFile_2022-11-26.csv
14,Jack Black,4/2/19,183,91,NewCombinedFile_2022-11-26.csv
15,Rock Royden,5/2/19 0:00,160,52,NewCombinedFile_2022-11-26.csv
16,Brandon Snads,10/2/19 0:00,175,80,NewCombinedFile_2022-11-26.csv
17,Jen Smith,5/2/19 0:00,153,50,NewCombinedFile_2022-11-26.csv
18,Sam Smith,1/2/19 0:00,160,55,NewCombinedFile_2022-11-26.csv
19,Vartika Test3,5/2/20 0:00,153,50,NewCombinedFile_2022-11-26.csv
20,Vartika Test4,1/2/21 0:00,160,55,NewCombinedFile_2022-11-26.csv
21,Vartika Test5,9/2/20,170,75,NewCombinedFile_2022-11-26.csv
22,Jane Smith,9/2/19,170,75,NewCombinedFile_2022-11-26.csv
23,Jane Jackson,9/3/19,172,74,NewCombinedFile_2022-11-26.csv
24,Becky Jackson,4/3/19,165,70,NewCombinedFile_2022-11-26.csv
25,Vartika Test6,2/8/20,180,100,NewCombinedFile_2022-11-26.csv
26,John Smithe,3/8/19,185,101,NewCombinedFile_2022-11-26.csv
27,Brett Smithe,5/8/19,179,99,NewCombinedFile_2022-11-26.csv
28,John Smith,2/8/19,180,100,NewCombinedFile_2022-11-26.csv
29,Rock Royden,2019-05-02 00:00:00,160,52,EXCELtest2.xlsx
30,Brandon Snads,2019-10-02 00:00:00,175,80,EXCELtest2.xlsx
31,Jen Smith,2019-05-02 00:00:00,153,50,EXCELtest.xlsx
32,Sam Smith,2019-01-02 00:00:00,160,55,EXCELtest.xlsx
33,Vartika Test3,2020-05-02 00:00:00,153,50,EXCELtest3.xlsx
34,Vartika Test4,2021-01-02 00:00:00,160,55,EXCELtest3.xlsx
35,Vartika Test3,2020-05-02 00:00:00,153,50,EXCELtest4.xlsx
36,Vartika Test4,2021-01-02 00:00:00,160,55,EXCELtest4.xlsx
37,Vartika Test8,2022-01-02 00:00:00,160,55,EXCELtest4.xlsx
38,Vartika Test5,09/02/2020,170,75,JSONtest4.json
39,Vartika Test9,09/02/2021,170,75,JSONtest5.json
40,Jane Smith,09/02/2019,170,75,JSONtest.json
41,Jane Jackson,09/03/2019,172,74,JSONtest2.json
42,Becky Jackson,04/03/2019,165,70,JSONtest3.json
43,Vartika Test6,02/08/2020,180,100,XMLtest4.xml
44,Vartika Test10,02/08/2021,180,100,XMLtest5.xml
45,John Smithe,03/08/2019,185,101,XMLtest2.xml
46,Brett Smithe,05/08/2019,179,99,XMLtest3.xml
47,John Smith,02/08/2019,180,100,XMLtest.xml

Enter code in the cell below.

* Add code in the cell below to save your new dataframe as a csv file. (Hint - It's OK to reuse code from earlier in the assignment.)

In [18]:

# YOUR CODE HERE
# Save the dataframe to a new combined csv file.

# Add today's date to the name of the new file.
from datetime import date
today = date.today()
print(today)

filename = str(file_path) + '/' + 'NewCombinedFile_' + str(today) + '.csv'
print(filename)

df.to_csv(filename, index=False)
print('File saved.')

2022-11-26
/Users/vartika/Desktop/01 Vartika/01_software_coding/python combine files /exerPythCombineFiles-1/FileTypes/NewCombinedFile_2022-11-26.csv
File saved.